services:
  node_iot_main:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    env_file:
      - ./.env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: covid
      MYSQL_USER: covid_user
      MYSQL_PASSWORD: covid_password
    volumes:
      - db_data:/var/lib/mysql
      - ./covid_cases_final.sql:/docker-entrypoint-initdb.d/covid_cases_final.sql # Mount ไฟล์ SQL โดยตรง
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    restart: always
volumes:
  db_data:
